sudo: true
dist: trusty
language: python
python:
- '3.4'
- '3.5'
env:
- TOX_ENV=安裝
- TOX_ENV=flake8
install:
- sudo apt-get install normalize-audio
- pip install tox
branches:
  only:
  - master
script:
- tox -e $TOX_ENV

