sudo: true
dist: trusty
language: python
python:
- '3.4'
- '3.5'
env:
- TOX_ENV=flake8
- TOX_ENV=test
- TOX_ENV=check_migration
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - linux-libc-dev
      - gcc-multilib
      - automake
      - libtool
      - zlib1g-dev
      - libbz2-dev
      - liblzma-dev
      - libboost-all-dev
      - libgoogle-perftools-dev
      - cmake
      - csh
install:
- sudo apt-get install normalize-audio
- pip install tox python-coveralls
- pip install https://github.com/a8568730/django/archive/url_prefix_unicode.zip
branches:
  only:
  - master
script:
- tox -e $TOX_ENV
after_success:
- coverage report
- coveralls

