# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-19 02:45


from 臺灣言語工具.解析整理.文章粗胚 import 文章粗胚
from 臺灣言語工具.音標系統.閩南語.臺灣閩南語羅馬字拼音 import 臺灣閩南語羅馬字拼音
from 臺灣言語工具.解析整理.拆文分析器 import 拆文分析器
from 語言模型.models import 語言模型表
from 語料庫.models import 語料表
from 臺灣言語工具.解析整理.解析錯誤 import 解析錯誤


def 匯入校對語料():
    for 句物件 in _校對語句():
        語言模型表.objects.get_or_create(分詞=句物件.轉音(臺灣閩南語羅馬字拼音).看分詞())


def _校對語句():
    for 語料 in 語料表.objects.filter(校對者__isnull=False):
        try:
            yield 拆文分析器.對齊句物件(
                語料.漢字,
                文章粗胚.建立物件語句前處理減號(臺灣閩南語羅馬字拼音, 語料.本調臺羅)
            )
        except 解析錯誤:
            pass
