# Generated by Django 2.1.dev20171211082156 on 2017-12-11 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='語料庫用字',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('漢字', models.CharField(db_index=True, max_length=20)),
                ('羅馬字', models.CharField(db_index=True, max_length=20)),
                ('分詞', models.CharField(db_index=True, max_length=20)),
                ('出處', models.TextField()),
                ('備註', models.TextField()),
            ],
        ),
    ]
