# Generated by Django 2.1.dev20171211115128 on 2017-12-11 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('用字規範', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='語料庫用字',
            options={'verbose_name': '語料庫補字', 'verbose_name_plural': '語料庫補字'},
        ),
    ]
