# Generated by Django 2.1.dev20171228091429 on 2017-12-28 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('用字規範', '0003_auto_20171211_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='語料庫用字',
            name='修改時間',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
