# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('語料庫', '0001_狀況表'),
    ]

    operations = [
        migrations.AddField(
            model_name='語料表',
            name='備註',
            field=models.TextField(blank=True),
        ),
    ]
