# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 06:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('語料庫', '0002_語料表_備註'),
    ]

    operations = [
        migrations.CreateModel(
            name='校對表',
            fields=[
            ],
            options={
                'verbose_name': '1.校對表',
                'verbose_name_plural': '1.校對表',
                'proxy': True,
                'indexes': [],
            },
            bases=('語料庫.語料表',),
        ),
        migrations.CreateModel(
            name='檢查表',
            fields=[
            ],
            options={
                'verbose_name': '2.檢查表',
                'verbose_name_plural': '2.檢查表',
                'proxy': True,
                'indexes': [],
            },
            bases=('語料庫.語料表',),
        ),
        migrations.AlterField(
            model_name='語料表',
            name='校對時間',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='語料表',
            name='音檔',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='資料',
                to='語料庫.音檔表'),
        ),
    ]
