# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 09:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('語料庫', '0003_語料表_校對時間'),
    ]

    operations = [
        migrations.AddField(
            model_name='語料表',
            name='檢查時間',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='語料表',
            name='檢查者',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='語料表',
            name='校對者',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
