# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 04:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('語料庫', '0004_auto_20170911_1716'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kaldi篩掉表',
            fields=[
            ],
            options={
                'verbose_name': 'Kaldi篩掉表',
                'indexes': [],
                'verbose_name_plural': 'Kaldi篩掉表',
                'proxy': True,
            },
            bases=('語料庫.語料表',),
        ),
        migrations.CreateModel(
            name='討論表',
            fields=[
            ],
            options={
                'verbose_name': '討論表',
                'indexes': [],
                'verbose_name_plural': '討論表',
                'proxy': True,
            },
            bases=('語料庫.校對表',),
        ),
    ]
