# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('語料庫', '0005_kaldi篩掉表_討論表'),
    ]

    operations = [
        migrations.AddField(
            model_name='語料表',
            name='愛先做無',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
