# Generated by Django 2.1.dev20171123073329 on 2017-11-23 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('語料庫', '0006_語料表_愛先做無'),
    ]

    operations = [
        migrations.CreateModel(
            name='對齊狀態表',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('狀態', models.CharField(max_length=30)),
                ('語料', models.OneToOneField(default=None, null=True,
                                            on_delete=django.db.models.deletion.CASCADE,
                                            related_name='對齊狀態', to='語料庫.語料表')),
            ],
        ),
    ]
