# Generated by Django 2.1.dev20171124070830 on 2017-11-24 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('語料庫', '0007_對齊狀態表'),
    ]

    operations = [
        migrations.AlterField(
            model_name='對齊狀態表',
            name='語料',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='對齊狀態', to='語料庫.語料表'),
        ),
    ]
