# Generated by Django 2.1.dev20171123070253 on 2017-11-23 07:05

from django.db import migrations, models
import django.db.models.deletion
from 校對工具.檢查本調拼音 import 判斷本調拼音


def 初始對齊狀態(apps, editor):
    語料表 = apps.get_model('語料庫', '語料表')
    對齊狀態表 = apps.get_model('語料庫', '對齊狀態表')
    for 一語料 in 語料表.objects.all():
        狀態字串 = 判斷本調拼音(一語料.漢字, 一語料.本調臺羅)
        一狀態 = 對齊狀態表(狀態=狀態字串, 語料=一語料)
        一狀態.save()


class Migration(migrations.Migration):

    dependencies = [
        ('語料庫', '0007_語料表_愛先做無'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='語料表',
            name='對齊狀態',
        ),
        migrations.AddField(
            model_name='對齊狀態表',
            name='語料',
            field=models.OneToOneField(
                default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='對齊狀態', to='語料庫.語料表'),
        ),
        migrations.RunPython(初始對齊狀態, lambda *x:x)
    ]
