# Generated by Django 2.1.dev20171121103623 on 2017-11-22 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('語料庫', '0007_語料表_愛先做無'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='語料表',
            name='對齊狀態',
        ),
        migrations.AddField(
            model_name='對齊狀態表',
            name='語料',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='對齊狀態', to='語料庫.語料表'),
        ),
    ]
