# Generated by Django 2.1.dev20171130075255 on 2017-12-01 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('語料庫', '0008_對齊狀態表_不可為null'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='校對表',
            options={'verbose_name': '校對表', 'verbose_name_plural': '校對表'},
        ),
        migrations.AlterModelOptions(
            name='檢查表',
            options={'verbose_name': '檢查表', 'verbose_name_plural': '檢查表'},
        ),
    ]
