# Generated by Django 2.1.dev20171211013600 on 2017-12-11 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('語料庫', '0010_auto_20171208_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='語料狀況表',
            name='Kaldi輸出',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='語料狀況表',
            name='確定有校對',
            field=models.BooleanField(default=False),
        ),
    ]
