# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-23 03:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='口語辭典表',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('字分詞陣列', models.CharField(max_length=1000, unique=True)),
            ],
        ),
    ]
