# Generated by Django 2.1.dev20171207101724 on 2017-12-08 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('語料庫', '0010_auto_20171208_1359'),
    ]

    operations = [
        migrations.CreateModel(
            name='對齊狀態表',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('狀態', models.CharField(max_length=30)),
                ('語料', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='對齊狀態', to='語料庫.語料表')),
            ],
        ),
    ]
