# Generated by Django 2.1.dev20171208064932 on 2017-12-08 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('檢查工具', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='對齊狀態表',
            name='口語調空白',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='對齊狀態表',
            name='本調空白',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
