# Generated by Django 2.1.dev20171208065414 on 2017-12-08 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('檢查工具', '0002_auto_20171208_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='對齊狀態表',
            name='口語調輕聲符',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
