# Generated by Django 2.1.dev20171208070343 on 2017-12-08 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('檢查工具', '0003_對齊狀態表_口語調輕聲符'),
    ]

    operations = [
        migrations.AddField(
            model_name='對齊狀態表',
            name='本調口語調對應',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
