# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 00:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('校對工具', '0002_匯入辭典'),
    ]

    operations = [
        migrations.DeleteModel(
            name='辭典表',
        ),
    ]
